# Generated by Django 4.2 on 2024-03-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_created_at_remove_profile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Interests'),
        ),
    ]
